plots:
	poetry run python analyse_results.py ../results/lm/*.tsv  --hue dimension --function link_distributions --adjacency ../results/lm/A.txt -o lm.pdf
	poetry run python analyse_results.py ../results/sbm2/*.tsv  --hue dimension --function link_auc --adjacency ../results/sbm2/A.txt -o sbm2.pdf
	poetry run python analyse_results.py ../results/sbm3/*.tsv  --hue dimension --function link_auc --adjacency ../results/sbm3/A.txt -o sbm3.pdf

